### ISSUE TITLE
massive request for 'app.api.surehub.io' since v1.1.5

### ISSUE THREAD

**Issue by Scrounger** [Sickboy78/ioBroker.sureflap#33] opened 2023-01-14 14:59 UTC
**Describe the bug**  
Yesterday i updated to v1.1.5. Now i discovered that there are a lot of reqeusts for 'app.api.surehub.io' every seconds.

**To Reproduce**  
1. start the adapter and listen to traffic

**Expected behavior**  
As in version v1.1.2 only one request per minute.

![grafik](https://user-images.githubusercontent.com/6370451/212478355-06c3fec6-38ef-4f9c-a8aa-3cdf39af0e15.png)

**Comment by Sickboy78** [comment] 2023-01-14 17:43
Hi!

In the future it would be great, if you could name the tool and version, you are posting screenshots from, so I don't have to reverse image search, what you are using.

There were no changes to the request frequency since version 1.2.
The general data is requested every 10s and the history and reports (feeder+felaqua consumption) every minute.
If you set the log level in iobroker for the sureflap adapter to silly and then filter the protocoll for sureflap and silly, it should show you all outgoing requests like in the attached screenshot.

![grafik](https://user-images.githubusercontent.com/8673383/212486979-b3d6a4c0-e487-4b91-aea8-71ae5bd503b5.png)

If there are actually requests more often for you, please make a screenshot and post it here, so I can analyse.

As for your screenshot, it seems you are using AdGuard Home?! And the shown requests are not data but DNS requests to resolve the DNS name to an IPv4 (A) or IPv6 (AAAA) address. There have been bug reports for AdGuard Home which describe the same problem (e.g. https://github.com/AdguardTeam/AdGuardHome/issues/3707).
Please try the following and see if the problem persists:
Restart AdGuard Home.
Update AdGuard to latest version.
Restart you computer.

Hope this helps.
Best Regards

**Comment by Sickboy78** [comment] 2023-02-01 21:24
Closing. Not reproducible.

**Closed by Sickboy78** 2023-02-01 21:24 UTC
